// This file is auto-generated by TanStack Router
// It's a placeholder and will be updated when routes are added

import { rootRoute } from './routes/__root'
import { indexRoute } from './routes/index'

export const routeTree = rootRoute.addChildren([indexRoute])

declare module '@tanstack/react-router' {
  interface FileRoutesByFullPath {
    '/': any
  }
}
